coverage:
  status:
    # PRs only
    patch:
      default:
        threshold: 0.1%
ignore:
  - "Sources/SwiftInspectorCommands/Tests"
  - "Sources/SwiftInspectorAnalyzers/Tests"
  - "Sources/SwiftInspectorVisitors/Tests"
