coverage:
  status:
    # PRs only
    project:
      default:
        threshold: 0.25%
ignore:
  - "Sources/SwiftInspectorAnalyzers/Tests"
  - "Sources/SwiftInspectorCommands/Tests"
  - "Sources/SwiftInspectorTestHelpers/Tests"
  - "Sources/SwiftInspectorVisitors/Tests"
