name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode 13.3
      run: xcversion select 13.3

    - name: Build project
      run: swift build

    - name: Run tests and gather code coverage
      run: swift test --enable-code-coverage

    - name: Prepare code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/SwiftInspectorPackageTests.xctest/Contents/MacOS/SwiftInspectorPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - name: Upload code coverage
      run: bash <(curl https://codecov.io/bash)
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
